name: Reusable docker build workflow

inputs:
  PROJECT:
    required: true
    description: "The rush project to build from"
  DOCKERFILE:
    required: true
    description: "The location of the dockerfile relative to monorepo root"

runs:
  using: "composite"
  steps:
    - name: Rush deploy
      shell: bash
      run: rush deploy --project @tinyburg/${{ inputs.PROJECT }} --create-archive ${{ inputs.PROJECT }}.zip --create-archive-only --overwrite

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        platforms: linux/amd64,linux/arm64
        dockerfile: ${{ inputs.DOCKERFILE }}
        tags: ghcr.io/leonitousconforti/tinyburg/${{ inputs.PROJECT }}:latest
        build-args: |
          GIT_SHA=$GITHUB_SHA
