name: Reusable docker build workflow

inputs:
  PROJECT:
    required: true
    description: "The rush project to build from"
  DOCKERFILE:
    required: true
    description: "The location of the dockerfile relative to monorepo root"
  TAG:
    required: true
    description: "THe tag for the docker image"

runs:
  using: "composite"
  steps:
    - name: "placeholder"
      shell: bash
      run: echo "Hi, mom!"
