hoist: false
hoistPattern: []
autoInstallPeers: false
strictPeerDependencies: true
publicHoistPattern:
  - "vitest"
  - "@types/*"
  - "@vitest/*"
  - "@effect/vitest"

recursiveInstall: true
dedupePeerDependents: false
linkWorkspacePackages: true
hoistWorkspacePackages: false
preferWorkspacePackages: true
resolvePeersFromWorkspaceRoot: false

overrides:
  "@effect/docgen>typescript": "6.0.3"
  "madge>typescript": "6.0.3"

peerDependencyRules:
  allowedVersions:
    typescript: "6.0.3"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  frida: true
  msgpackr-extract: true
  sharp: true

packages:
  - apps/*
  - examples/*
  - packages/*
  - scratchpad

minimumReleaseAgeExclude:
    - "effect-oidc"
    - "@efffrida/*"
    - "@effect/*"
    - "effect"
