hoist: false
hoistPattern: []
autoInstallPeers: false
strictPeerDependencies: true
publicHoistPattern:
  - "vitest"
  - "@types/*"
  - "@vitest/*"
  - "@effect/vitest"

recursiveInstall: true
dedupePeerDependents: false
linkWorkspacePackages: true
hoistWorkspacePackages: false
preferWorkspacePackages: true
resolvePeersFromWorkspaceRoot: false

overrides:
  "@effect/platform-node-shared": "4.0.0-beta.100"
  "@effect/docgen>typescript": "7.0.2"
  "madge>typescript": "7.0.2"

peerDependencyRules:
  allowedVersions:
    typescript: "6.0.3"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  frida: true
  msgpackr-extract: true
  sharp: true

packages:
  - apps/*
  - examples/*
  - packages/*
  - scratchpad
