version: "3.9"
services:
  web:
    image: ghcr.io/leonitousconforti/tinyburg/authproxy
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis_cache
      - postgres_db
    environment:
      - REDIS_URL=redis://redis_cache:6379
      - DATABASE_URL=postgres://postgres:password@postgres_db:5432/authproxy?sslmode=disable
    env_file: .env

  # Redis cache
  redis_cache:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dumps:/data/

  # Postgres database
  postgres_db:
    image: "postgres:latest"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authproxy
    ports:
      - "5432:5432"

  # pgweb App
  pgweb_app:
    image: sosedoff/pgweb:latest
    restart: unless-stopped
    ports:
      - "5001:8081"
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres_db:5432/authproxy?sslmode=disable

  # redis insights
  redis_insight:
    image: "redislabs/redisinsight:latest"
    restart: unless-stopped
    ports:
      - "5002:8001"
    depends_on:
      - redis_cache
    volumes:
      - redis-insights:/db

volumes:
  postgres-data:
  redis-dumps:
  redis-insights:
