version: "3"
services:
  web:
    image: "ghcr.io/leonitousconforti/tinyburg/authproxy:latest"
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis_cache
      - postgres_db
    env_file: .env
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis_cache:6379
      - DATABASE_URL=postgres://postgres:password@postgres_db:5432/authproxy
    networks:
      - authproxy_mesh

  # Redis cache
  redis_cache:
    image: "redis:latest"
    restart: unless-stopped
    volumes:
      - redis-dumps:/data/
    networks:
      - authproxy_mesh

  # Postgres database
  postgres_db:
    image: "postgres:latest"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - authproxy_mesh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authproxy

  # pgweb app
  pgweb_app:
    image: sosedoff/pgweb:latest
    restart: unless-stopped
    ports:
      - "5001:8081"
    depends_on:
      - postgres_db
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:password@postgres_db:5432/authproxy?sslmode=disable
    networks:
      - authproxy_mesh

  # redis insights
  redis_insight:
    image: "redislabs/redisinsight:latest"
    restart: unless-stopped
    ports:
      - "5002:8001"
    depends_on:
      - redis_cache
    volumes:
      - redis-insights:/db
    networks:
      - authproxy_mesh

volumes:
  postgres-data:
  redis-dumps:
  redis-insights:

networks:
  authproxy_mesh: {}
