version: "3.8"
services:
    envoy:
        image: architect_envoy:latest
        build:
            context: ./envoy
            dockerfile: Dockerfile
        networks:
            - envoymesh
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8080:8080"
            - "8081:8081"

    emulator:
        image: tinyburg/architect:emulator-9322596_sysimg-31-google-apis-x64_frida-16.0.10
        shm_size: 128M
        devices: [/dev/kvm]
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 5G
        environment:
            - TURN=$HOSTNAME
        build:
            context: ./emulator
            dockerfile: Dockerfile
        ports:
            - "27042:27042"
        networks:
            envoymesh:
                aliases:
                    - emulator

    jwt_signer:
        image: architect_jwt_signer:latest
        build:
            context: ./jwt-provider
            dockerfile: Dockerfile
        networks:
            envoymesh:
                aliases:
                    - jwt_signer

    frontend:
        image: architect_frontend:latest
        build:
            context: ./node_modules/@tinyburg/architect-viewer/
            dockerfile: Dockerfile
        networks:
            envoymesh:
                aliases:
                    - frontend

    coturn_server:
        image: coturn/coturn:alpine
        network_mode: "host"

networks:
    envoymesh: {}
