version: "3.8"
services:
    envoy:
        image: architect_envoy:latest
        build:
            context: ./envoy
            dockerfile: Dockerfile
        networks:
            - envoymesh
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8080:8080"
            - "8081:8081"

    emulator:
        image: architect_emulator:latest
        shm_size: 128M
        devices: [/dev/kvm]
        build:
            context: ./emulator
            dockerfile: Dockerfile
        networks:
            envoymesh:
                aliases:
                    - emulator

    jwt_signer:
        image: architect_jwt_signer:latest
        build:
            context: ./jwt-provider
            dockerfile: Dockerfile
        networks:
            envoymesh:
                aliases:
                    - jwt_signer

    frontend:
        image: architect_frontend:latest
        build:
            context: ./node_modules/@tinyburg/architect-viewer/
            dockerfile: Dockerfile
        networks:
            envoymesh:
                aliases:
                    - frontend

networks:
    envoymesh: {}
