version: "3"
services:
  envoy:
    image: ghcr.io/leonitousconforti/tinyburg/architect_envoy:latest
    build:
      context: ./envoy
    networks:
      - envoymesh
    ports:
      - "0:8080"

  emulator:
    image: ghcr.io/leonitousconforti/tinyburg/architect_emulator:10086546_sys-30-google-apis-x64-r12_frida-16.0.19
    shm_size: 128
    devices: [/dev/kvm]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 5G
    build:
      context: ./emulator
    volumes:
      - emulator_data:/android/avd-home/Pixel2.avd/
    ports:
      - "0:5554"
      - "0:5555"
      - "0:8554"
      - "0:27042"
    networks:
      envoymesh:
        aliases:
          - emulator

  jwt_signer:
    image: ghcr.io/leonitousconforti/tinyburg/architect_jwt_signer:latest
    build:
      context: ./jwt-provider
    expose:
      - "8080"
    networks:
      envoymesh:
        aliases:
          - jwt_signer

  frontend:
    image: ghcr.io/leonitousconforti/tinyburg/architect_frontend_instructions:latest
    build:
      context: ./frontend-placeholder
    expose:
      - "8080"
    networks:
      envoymesh:
        aliases:
          - frontend

networks:
  envoymesh: {}

volumes:
  emulator_data:
