/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-pet-data.js
 *
 * With TinyTower version: 4.26.1
 *
 * On: Sun, 08 Oct 2023 08:42:16 GMT
 */

export const pets = {} as const;
export type Pet = typeof pets;
