/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-pet-data.js
 *
 * With TinyTower version: 4.24.0
 *
 * On: Mon, 07 Aug 2023 23:54:01 GMT
 */

export const pets = {} as const;
export type Pet = typeof pets;
