version: "3.8"
services:
    envoy:
        image: architect_viewer_envoy:latest
        build:
            context: ./envoy
            dockerfile: Dockerfile
        networks:
            - envoymesh
        expose:
            - "8080"
            - "8081"
        ports:
            - "8080:8080"
            - "8081:8081"

    emulator:
        image: architect_viewer_emulator:latest
        build:
            context: ./../../packages/architect/emulator
            dockerfile: Dockerfile
        devices: [/dev/kvm]
        shm_size: 128M
        networks:
            envoymesh:
                aliases:
                    - emulator
        expose:
            - "5554"
            - "5555"
            - "8554"
            - "27042"
        ports:
            - "8554:8554"

    jwt_signer:
        image: emulator_jwt_signer:latest
        build:
            context: ./jwt-provider
            dockerfile: Dockerfile
        networks:
            envoymesh:
                aliases:
                    - jwt_signer
        expose:
            - "8080"

    frontend:
        image: architect_viewer_frontend:latest
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            envoymesh:
                aliases:
                    - frontend
        expose:
            - "8080"

networks:
    envoymesh: {}
