name: Reusable docker build workflow

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      tag:
        required: true
        type: string
