name: Reusable rush build workflow

inputs:
  BUILD_PARAMETERS:
    required: false
    description: "Build parameters to pass to rush build"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: pnpm/action-setup@v4
      with:
        version: 7.33.5

    - if: runner.os == 'Linux'
      name: Start xvfb
      shell: bash
      run: |
        sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Setup rush build cache
      uses: gigara/rush-cache@v2

    - name: Setup rush install cache
      uses: actions/cache@v3
      with:
        path: |
          common/temp/install-run
          ~/.rush
        key: rush-install-run-cache-${{ hashFiles('rush.json') }}

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: |
          common/temp/pnpm-store
          ~/.cache/puppeteer
        key: pnpm-cache-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Setup apks cache
      uses: actions/cache@v3
      with:
        path: packages/apks/downloads
        key: apks-cache

    - name: Rush Install
      shell: bash
      run: |
        node common/scripts/install-run-rush.js install

    - name: Rush build and test
      shell: bash
      run: node common/scripts/install-run-rush.js test --timeline --production ${{ inputs.BUILD_PARAMETERS }}
