name: Reusable docker build workflow

inputs:
  PROJECT:
    required: true
    description: "The rush project to build from"
  DOCKERFILE:
    required: true
    description: "The location of the dockerfile relative to monorepo root"
  GITHUB_TOKEN:
    required: true
    description: "The github token to use for docker login"

runs:
  using: "composite"
  steps:
    - name: Rush deploy
      shell: bash
      run: node common/scripts/install-run-rush.js deploy --project @tinyburg/${{ inputs.PROJECT }} --create-archive ${{ inputs.PROJECT }}.zip --create-archive-only --overwrite

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Login to GitHub Container Registry"
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ${{ inputs.DOCKERFILE }}
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        tags: ghcr.io/leonitousconforti/tinyburg/${{ inputs.PROJECT }}:latest
        build-args: |
          GIT_SHA=${{ github.sha }}
