/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-bitbook-data.js
 *
 * With TinyTower version: 5.2.1
 *
 * On: Wed, 08 May 2024 23:05:51 GMT
 */

export enum BBEventType {
    None = "None",
    FullyStocked = "FullyStocked",
    FloorClosed = "FloorClosed",
    CasinoWin = "CasinoWin",
    Checkout = "Checkout",
    Checkin = "Checkin",
    BitizenHired = "BitizenHired",
    NewFloor = "NewFloor",
    Character = "Character",
    Birthday = "Birthday",
    BitizenHiredLow = "BitizenHiredLow",
    NewRoomate = "NewRoomate",
    NewPet = "NewPet",
}
export enum PostMediaType {
    None = "None",
    AtlasImage = "AtlasImage",
    WWWLink = "WWWLink",
}

export const posts = [] as const;
export type Post = (typeof posts)[number];
