/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-elevator-data.js
 *
 * With TinyTower version: 5.2.1
 *
 * On: Wed, 08 May 2024 23:06:24 GMT
 */
export declare const upgradeElevatorCost: (liftSpeed: number) => number;
export declare const numberElevators: 44;
export declare const elevators: readonly [{
    readonly name: "Trusty Rusty";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "elevatorflicker";
        readonly x: 0;
        readonly y: 65;
        readonly frontlayer: 1;
        readonly ftime: "0.1";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "sparks";
        readonly x: 2;
        readonly y: 34;
        readonly ftime: "0.05";
        readonly frontlayer: 1;
        readonly additive: true;
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Steel Series SE";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "elevator1anim";
        readonly x: 0;
        readonly y: 19;
        readonly ftime: "1";
    }];
}, {
    readonly name: "Pullman Prestige";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "elevator2anim";
        readonly x: 3;
        readonly y: 52;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "Litestripe 3000";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "elevator3neon";
        readonly x: 0;
        readonly y: 65;
        readonly cyclecolor: "8";
        readonly additive: true;
    }];
}, {
    readonly name: "Disco Lift";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "elevator4floor";
        readonly x: 2;
        readonly y: 53;
        readonly ftime: "0.35";
    }, {
        readonly element: "discoball";
        readonly x: 5;
        readonly y: 12;
        readonly ftime: "0.2";
    }, {
        readonly element: "discoball";
        readonly x: 5;
        readonly y: 12;
        readonly ftime: "0.2";
        readonly additive: true;
        readonly cyclecolor: "8";
    }, {
        readonly element: "elevator4color";
        readonly x: 2;
        readonly y: 51;
        readonly frontlayer: 1;
        readonly additive: true;
        readonly ftime: "0.08";
        readonly cyclecolor: "8";
    }];
}, {
    readonly name: "Egyptian Lift";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "torch";
        readonly x: 2;
        readonly y: 27;
        readonly ftime: "0.13";
    }, {
        readonly element: "torch";
        readonly x: 24;
        readonly y: 27;
        readonly ftime: "0.13";
        readonly startframe: 4;
    }];
}, {
    readonly name: "NB200 Commercial Lift";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "elevlight";
        readonly x: 7;
        readonly y: 17;
        readonly ftime: "0.13";
    }];
}, {
    readonly name: "Insta-Lift 200 SE";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "elevstrip";
        readonly x: 7;
        readonly y: 17;
        readonly ftime: "0.13";
    }];
}, {
    readonly name: "Ultra-Lift 3000 Extreme";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "goldstrip";
        readonly x: 7;
        readonly y: 17;
        readonly ftime: "0.13";
    }, {
        readonly element: "goldshine";
        readonly x: 0;
        readonly y: 65;
        readonly ftime: "0.04";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Infini-lift lightspeed";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "bluring";
        readonly x: 4;
        readonly y: 5;
        readonly ftime: "0.1";
    }, {
        readonly element: "bluring";
        readonly x: 21;
        readonly y: 5;
        readonly ftime: "0.1";
    }, {
        readonly element: "blubars";
        readonly x: 9;
        readonly y: 9;
        readonly ftime: "0.1";
    }, {
        readonly element: "blublink";
        readonly x: 4;
        readonly y: 17;
        readonly ftime: "0.25";
    }, {
        readonly element: "bludoor";
        readonly x: 5;
        readonly y: 51;
        readonly ftime: "0.05";
    }];
}, {
    readonly name: "Glass Lift";
    readonly yoffset: "-12";
}, {
    readonly name: "Police Box";
    readonly yoffset: "-12";
}, {
    readonly name: "Metal Cage";
    readonly yoffset: "-12";
}, {
    readonly name: "Halloween Lift";
    readonly holiday: "Halloween";
    readonly yoffset: "-12";
}, {
    readonly name: "Holiday Lift";
    readonly holiday: "The Holidays";
    readonly yoffset: "-12";
    readonly animations: readonly [{
        readonly element: "xmaslift";
        readonly x: 0;
        readonly y: 85;
        readonly ftime: "0.5";
    }];
}, {
    readonly name: "Marble Lift";
    readonly yoffset: "-12";
}, {
    readonly name: "Hydro Lift";
    readonly yoffset: "-256";
    readonly animations: readonly [{
        readonly element: "waterlift";
        readonly x: 0;
        readonly y: 3;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Tree Lift";
    readonly yoffset: "-12";
}, {
    readonly name: "Easter Lift";
    readonly hidden: true;
    readonly yoffset: "-6";
}, {
    readonly name: "Independence Lift";
    readonly holiday: "Independence Day";
    readonly yoffset: "-11";
}, {
    readonly name: "Liberty Lift";
    readonly holiday: "Independence Day";
    readonly yoffset: "-11";
}, {
    readonly name: "Pineapple";
    readonly hidden: true;
    readonly yoffset: "-14";
}, {
    readonly name: "Jungle";
    readonly holiday: "Summer";
    readonly yoffset: "-13";
    readonly doorOffsetX: "1";
}, {
    readonly name: "pumpkin cage";
    readonly hidden: true;
    readonly yoffset: "-10";
}, {
    readonly name: "iron maiden";
    readonly holiday: "Halloween";
    readonly yoffset: "-10";
}, {
    readonly name: "green present";
    readonly holiday: "The Holidays";
    readonly yoffset: "-6";
}, {
    readonly name: "ski lift";
    readonly hidden: true;
    readonly yoffset: "-13";
    readonly xDoorOffset: "1";
    readonly yDoorOffset: "-1";
}, {
    readonly name: "Elevator of Freedom";
    readonly yoffset: "-13";
    readonly hidden: true;
}, {
    readonly name: "Cooling Elevator";
    readonly yoffset: "-13";
    readonly yDoorOffset: "3";
    readonly hidden: true;
}, {
    readonly name: "Ice Cream";
    readonly yoffset: "-18";
    readonly holiday: "IceCream";
}, {
    readonly name: "Lifeguard";
    readonly yoffset: "-16";
    readonly xoffset: "-2";
    readonly xDoorOffset: "2";
    readonly hidden: true;
    readonly holiday: "SummerEvent";
}, {
    readonly name: "Grim elevator";
    readonly yoffset: "-6";
    readonly xDoorOffset: "-3";
    readonly hidden: true;
    readonly holiday: "Halloween";
    readonly animations: readonly [{
        readonly element: "elevator31anim";
        readonly x: 12;
        readonly y: 18;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Coffin elevator";
    readonly yoffset: "-15";
    readonly yDoorOffset: "5";
    readonly hidden: true;
    readonly holiday: "Halloween";
    readonly animations: readonly [{
        readonly element: "elevator31anim";
        readonly x: 12;
        readonly y: 7;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Pilgrims elevator";
    readonly yoffset: "-10";
    readonly yDoorOffset: "-3";
    readonly xDoorOffset: "-7";
    readonly holiday: "Thanksgiving";
}, {
    readonly name: "Pumpkin elevator";
    readonly yoffset: "-1";
    readonly yDoorOffset: "-3";
    readonly xDoorOffset: "-7";
    readonly hidden: true;
    readonly holiday: "Thanksgiving";
}, {
    readonly name: "Jingle bells elevator";
    readonly xDoorOffset: "-3";
    readonly hidden: true;
    readonly holiday: "The Holidays";
}, {
    readonly name: "North pole elevator";
    readonly yoffset: "-6";
    readonly xDoorOffset: "-3";
    readonly yDoorOffset: "2";
    readonly holiday: "The Holidays";
}, {
    readonly name: "Heart elevator";
    readonly hidden: true;
    readonly yoffset: "-6";
    readonly xDoorOffset: "-3";
    readonly yDoorOffset: "2";
}, {
    readonly name: "Leprechaun beverage elevator";
    readonly hidden: true;
    readonly yoffset: "-8";
    readonly xDoorOffset: "1";
    readonly yDoorOffset: "-2";
    readonly animations: readonly [{
        readonly element: "elevator38anim";
        readonly x: 8;
        readonly y: 49;
        readonly frontlayer: 1;
        readonly additive: true;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "St. Patrick's hat elevator";
    readonly yoffset: "-13";
    readonly xDoorOffset: "-1";
}, {
    readonly name: "Bunny hop elevator";
    readonly hidden: true;
    readonly yoffset: "-7";
    readonly xDoorOffset: "-7";
}, {
    readonly name: "Egg basket elevator";
    readonly xoffset: "0";
    readonly xDoorOffset: "-2";
    readonly yDoorOffset: "-1";
}, {
    readonly name: "Blossom Tree Elevator";
    readonly hidden: true;
    readonly yoffset: "-8";
    readonly xDoorOffset: "-7";
}, {
    readonly name: "Bloom Elevator";
    readonly yoffset: "-8";
    readonly xDoorOffset: "-3";
}];
export type Elevator = (typeof elevators)[number];
//# sourceMappingURL=elevators.d.ts.map