/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-floor-data.js
 *
 * With TinyTower version: 5.2.1
 *
 * On: Wed, 08 May 2024 23:06:46 GMT
 */
export declare const buildFloorCost: (numFloors: number) => number;
export declare enum FloorType {
    None = "None",
    Food = "Food",
    Retail = "Retail",
    Entertainment = "Entertainment",
    Casino = "Casino",
    Hotel = "Hotel",
    Lobby = "Lobby",
    Creative = "Creative",
    Residential = "Residential",
    Empty = "Empty",
    Service = "Service",
    VIPLounge = "VIPLounge"
}
export declare const floors: readonly [{
    readonly name: "Sushi Bar";
    readonly type: FloorType.Food;
    readonly stockVar: 0;
}, {
    readonly name: "Mexican Food";
    readonly type: FloorType.Food;
    readonly stockVar: 1;
}, {
    readonly name: "Tea House";
    readonly type: FloorType.Food;
    readonly stockVar: 2;
}, {
    readonly name: "Vegan Food";
    readonly type: FloorType.Food;
    readonly stockVar: 3;
}, {
    readonly name: "Frozen Yogurt";
    readonly type: FloorType.Food;
    readonly stockVar: 4;
}, {
    readonly name: "Smoothie Shop";
    readonly type: FloorType.Food;
    readonly stockVar: 5;
}, {
    readonly name: "Sub Shop";
    readonly type: FloorType.Food;
    readonly stockVar: 6;
}, {
    readonly name: "Coffee House";
    readonly type: FloorType.Food;
    readonly stockVar: 7;
}, {
    readonly name: "Sky Burger";
    readonly type: FloorType.Food;
    readonly stockVar: 8;
}, {
    readonly name: "Asian Cuisine";
    readonly type: FloorType.Food;
    readonly stockVar: 9;
}, {
    readonly name: "Diner";
    readonly type: FloorType.Food;
    readonly stockVar: 10;
}, {
    readonly name: "Pub";
    readonly type: FloorType.Food;
    readonly stockVar: 11;
}, {
    readonly name: "Pizza Place";
    readonly type: FloorType.Food;
    readonly stockVar: 12;
}, {
    readonly name: "Scoops";
    readonly type: FloorType.Food;
    readonly stockVar: 13;
}, {
    readonly name: "Bakery";
    readonly type: FloorType.Food;
    readonly stockVar: 14;
}, {
    readonly name: "Fancy Cuisine";
    readonly type: FloorType.Food;
    readonly stockVar: 15;
}, {
    readonly name: "Barber Shop";
    readonly type: FloorType.Service;
    readonly stockVar: 16;
}, {
    readonly name: "Day Spa";
    readonly type: FloorType.Service;
    readonly stockVar: 17;
}, {
    readonly name: "Dentists Office";
    readonly type: FloorType.Service;
    readonly stockVar: 18;
}, {
    readonly name: "Doctors Office";
    readonly type: FloorType.Service;
    readonly stockVar: 19;
}, {
    readonly name: "Fortune Teller";
    readonly type: FloorType.Service;
    readonly stockVar: 20;
}, {
    readonly name: "Optometrist";
    readonly type: FloorType.Service;
    readonly stockVar: 21;
}, {
    readonly name: "Health Club";
    readonly type: FloorType.Service;
    readonly stockVar: 22;
}, {
    readonly name: "Martial Arts";
    readonly type: FloorType.Service;
    readonly stockVar: 23;
}, {
    readonly name: "Wedding Chapel";
    readonly type: FloorType.Service;
    readonly stockVar: 24;
}, {
    readonly name: "Laundromat";
    readonly type: FloorType.Service;
    readonly stockVar: 25;
}, {
    readonly name: "Private eye";
    readonly type: FloorType.Service;
    readonly stockVar: 26;
}, {
    readonly name: "Tutoring Center";
    readonly type: FloorType.Service;
    readonly stockVar: 27;
}, {
    readonly name: "Travel Agency";
    readonly type: FloorType.Service;
    readonly stockVar: 28;
}, {
    readonly name: "Ship & Print";
    readonly type: FloorType.Service;
    readonly stockVar: 29;
}, {
    readonly name: "Pharmacy";
    readonly type: FloorType.Service;
    readonly stockVar: 30;
}, {
    readonly name: "Bank";
    readonly type: FloorType.Service;
    readonly stockVar: 31;
}, {
    readonly name: "Arcade";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 32;
}, {
    readonly name: "Video Rental";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 33;
}, {
    readonly name: "Museum";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 34;
}, {
    readonly name: "Aquarium";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 35;
}, {
    readonly name: "Cineplex";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 36;
}, {
    readonly name: "Theater";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 37;
}, {
    readonly name: "Planetarium";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 38;
}, {
    readonly name: "Plainlake Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Sweetside Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Tuscana Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Lotus Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Moderna Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Chateau Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "50's Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Santa Fe Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Gothic Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Art Deco Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Rustic Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Eclectic Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Broadleaf Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Safari Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "70's Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Loft Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Mini Golf";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 55;
}, {
    readonly name: "Volleyball Club";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 56;
}, {
    readonly name: "Racquetball";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 57;
}, {
    readonly name: "__Empty String__";
    readonly type: FloorType.Empty;
}, {
    readonly name: "undefined";
    readonly type: FloorType.None;
}, {
    readonly name: "Bowling Alley";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 60;
}, {
    readonly name: "Cyber Cafe";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 61;
}, {
    readonly name: "Paintball Arena";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 62;
}, {
    readonly name: "Night Club";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 63;
}, {
    readonly name: "Casino";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 64;
}, {
    readonly name: "Comedy Club";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 65;
}, {
    readonly name: "Toy Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 66;
}, {
    readonly name: "Mapple Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 67;
}, {
    readonly name: "Book Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 68;
}, {
    readonly name: "Shoe Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 69;
}, {
    readonly name: "Hat Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 70;
}, {
    readonly name: "Record Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 71;
}, {
    readonly name: "Music Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 72;
}, {
    readonly name: "Bike Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 73;
}, {
    readonly name: "Comic Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 74;
}, {
    readonly name: "Furniture Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 75;
}, {
    readonly name: "Plant Nursery";
    readonly type: FloorType.Retail;
    readonly stockVar: 76;
}, {
    readonly name: "Fabric Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 77;
}, {
    readonly name: "Mens Fashion";
    readonly type: FloorType.Retail;
    readonly stockVar: 78;
}, {
    readonly name: "Womens Fashion";
    readonly type: FloorType.Retail;
    readonly stockVar: 79;
}, {
    readonly name: "Tech Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 80;
}, {
    readonly name: "Game Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 81;
}, {
    readonly name: "Tattoo Parlor";
    readonly type: FloorType.Creative;
    readonly stockVar: 82;
}, {
    readonly name: "Software Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 83;
}, {
    readonly name: "Pottery Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 84;
}, {
    readonly name: "Glass Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 85;
}, {
    readonly name: "Art Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 86;
}, {
    readonly name: "Photo Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 87;
}, {
    readonly name: "Fashion Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 88;
}, {
    readonly name: "Recording Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 89;
}, {
    readonly name: "Wood Shop";
    readonly type: FloorType.Creative;
    readonly stockVar: 90;
}, {
    readonly name: "Architect Office";
    readonly type: FloorType.Creative;
    readonly stockVar: 91;
}, {
    readonly name: "Graphic Design";
    readonly type: FloorType.Creative;
    readonly stockVar: 92;
}, {
    readonly name: "Film Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 93;
}, {
    readonly name: "Ad Agency";
    readonly type: FloorType.Creative;
    readonly stockVar: 94;
}, {
    readonly name: "Game Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 95;
}, {
    readonly name: "Cake Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 96;
}, {
    readonly name: "Soda Brewery";
    readonly type: FloorType.Creative;
    readonly stockVar: 97;
}, {
    readonly name: "High Tech Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Garden Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Baycrest Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Mismatch Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Nerd Cave Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Zen Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Beach Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Club Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Hacienda Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Greek Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Storage Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Brightpoint Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Cottage Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Greenwood Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Aquatic Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Stonecrest Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Bridgeview Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Fawlty Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Estate Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Pinehurst Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "HiFi Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Birchside Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Westgrove Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Plumbrook Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Glendale Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Ridgemill Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Goldcreek Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Silverwell Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Mesa Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Dover Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Mistmont Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Devonshire Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Mapleton Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Ivymoss Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Auto Dealer";
    readonly type: FloorType.Retail;
    readonly stockVar: 132;
}, {
    readonly name: "BBQ Place";
    readonly type: FloorType.Food;
    readonly stockVar: 133;
}, {
    readonly name: "Recycling";
    readonly type: FloorType.Service;
    readonly stockVar: 134;
}, {
    readonly name: "Floral Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 135;
}, {
    readonly name: "Rock Climbing";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 136;
}, {
    readonly name: "Millspring Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Security Office";
    readonly type: FloorType.Service;
    readonly stockVar: 138;
}, {
    readonly name: "Karaoke Club";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 139;
}, {
    readonly name: "Grocery Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 140;
}, {
    readonly name: "Pancake House";
    readonly type: FloorType.Food;
    readonly stockVar: 141;
}, {
    readonly name: "Laboratory";
    readonly type: FloorType.Creative;
    readonly stockVar: 142;
}, {
    readonly name: "Tiki Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Submarine Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Anti Grav Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Courthouse";
    readonly type: FloorType.Service;
    readonly stockVar: 146;
}, {
    readonly name: "Haunted House";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 147;
}, {
    readonly name: "Candle Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 148;
}, {
    readonly name: "Animation Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 149;
}, {
    readonly name: "Donut Shop";
    readonly type: FloorType.Food;
    readonly stockVar: 150;
}, {
    readonly name: "Egyptian Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Magic Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Roman Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Seafood";
    readonly type: FloorType.Food;
    readonly stockVar: 154;
}, {
    readonly name: "Jewelry Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 155;
}, {
    readonly name: "Mechanic";
    readonly type: FloorType.Service;
    readonly stockVar: 156;
}, {
    readonly name: "Billiard Hall";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 157;
}, {
    readonly name: "TV Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 158;
}, {
    readonly name: "Arctic Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Space Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Bachelor Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Archery Range";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 162;
}, {
    readonly name: "Pet Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 163;
}, {
    readonly name: "Chocolatier";
    readonly type: FloorType.Creative;
    readonly stockVar: 164;
}, {
    readonly name: "Italian Food";
    readonly type: FloorType.Food;
    readonly stockVar: 165;
}, {
    readonly name: "Fire Station";
    readonly type: FloorType.Service;
    readonly stockVar: 166;
}, {
    readonly name: "College Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Party Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Honey Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Ship Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Park";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 171;
}, {
    readonly name: "Surf Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 172;
}, {
    readonly name: "Stock Exchange";
    readonly type: FloorType.Service;
    readonly stockVar: 173;
}, {
    readonly name: "Clockmaker";
    readonly type: FloorType.Creative;
    readonly stockVar: 174;
}, {
    readonly name: "Cheese Shop";
    readonly type: FloorType.Food;
    readonly stockVar: 175;
}, {
    readonly name: "Temple Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Holiday Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Hot Dog Joint";
    readonly type: FloorType.Food;
    readonly stockVar: 178;
}, {
    readonly name: "Plumber";
    readonly type: FloorType.Service;
    readonly stockVar: 179;
}, {
    readonly name: "Circus";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 180;
}, {
    readonly name: "Home Supply";
    readonly type: FloorType.Retail;
    readonly stockVar: 181;
}, {
    readonly name: "Sculpting Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 182;
}, {
    readonly name: "Low Rent Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Sunset Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Pet Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Airline Food";
    readonly type: FloorType.Food;
    readonly stockVar: 186;
}, {
    readonly name: "Stables";
    readonly type: FloorType.Service;
    readonly stockVar: 187;
}, {
    readonly name: "Golf Sim";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 188;
}, {
    readonly name: "Robot Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 189;
}, {
    readonly name: "Costume Shop";
    readonly type: FloorType.Creative;
    readonly stockVar: 190;
}, {
    readonly name: "Theater Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Overgrown Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Reef Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Roman Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "horsefountain";
        readonly x: 69;
        readonly y: 45;
        readonly frontlayer: 1;
    }, {
        readonly element: "fountain";
        readonly x: 72;
        readonly y: 39;
        readonly ftime: "0.2";
        readonly frontlayer: 1;
    }, {
        readonly element: "floor1panels";
        readonly x: 3;
        readonly y: 10;
        readonly cyclecolor: "16";
        readonly additive: true;
    }];
}, {
    readonly name: "Egyptian Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Standard Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "New York Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "nywater";
        readonly x: 63;
        readonly y: 43;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Fun Fair Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "fairdoor";
        readonly x: 32;
        readonly y: 46;
        readonly ftime: "0.3";
    }, {
        readonly element: "fairlight";
        readonly x: 106;
        readonly y: 18;
        readonly ftime: "0.3";
    }];
}, {
    readonly name: "China Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "dragoneye";
        readonly x: 84;
        readonly y: 27;
        readonly ftime: "0.07";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "smoke";
        readonly x: 88;
        readonly y: 30;
        readonly ftime: "0.2";
        readonly additive: true;
    }];
}, {
    readonly name: "Europe Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "euroclock";
        readonly x: 5;
        readonly y: 19;
        readonly ftime: "4";
    }];
}, {
    readonly name: "Russia Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "glow";
        readonly x: 2;
        readonly y: 34;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 3;
    }, {
        readonly element: "glow";
        readonly x: 77;
        readonly y: 34;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }];
}, {
    readonly name: "NASA Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "nasascreen";
        readonly x: 3;
        readonly y: 30;
        readonly ftime: "0.3";
    }, {
        readonly element: "nasanum";
        readonly x: 68;
        readonly y: 6;
        readonly ftime: "1";
    }, {
        readonly element: "nasamap";
        readonly x: 77;
        readonly y: 30;
        readonly ftime: "0.1";
    }, {
        readonly element: "nasacomp";
        readonly x: 61;
        readonly y: 40;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Farm Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Island Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "rockwater";
        readonly x: 57;
        readonly y: 43;
        readonly ftime: "0.5";
    }];
}, {
    readonly name: "UFO Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "ufolight";
        readonly x: 78;
        readonly y: 26;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "British Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "glow";
        readonly x: 46;
        readonly y: 24;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }, {
        readonly element: "glow";
        readonly x: 106;
        readonly y: 24;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 2;
    }];
}, {
    readonly name: "Taj Mahal Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Neon Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "neonbar";
        readonly x: 0;
        readonly y: 39;
        readonly ftime: "0.2";
    }, {
        readonly element: "neontext";
        readonly x: 63;
        readonly y: 35;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Art Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "glow";
        readonly x: 29;
        readonly y: 27;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }];
}, {
    readonly name: "Greek Temple Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "greekfirea";
        readonly x: 10;
        readonly y: 16;
        readonly ftime: "0.15";
    }, {
        readonly element: "greekfireb";
        readonly x: 70;
        readonly y: 16;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Jungle Temple Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Dojo Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Halloween Lobby";
    readonly type: FloorType.Lobby;
    readonly holiday: "Halloween";
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "blinkeye";
        readonly x: 43;
        readonly y: 20;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blinkeye";
        readonly x: 37;
        readonly y: 25;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blinkeye";
        readonly x: 41;
        readonly y: 32;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "spookcandle";
        readonly x: 92;
        readonly y: 26;
        readonly additive: true;
        readonly ftime: "0.1";
    }, {
        readonly element: "spookcandle";
        readonly x: 112;
        readonly y: 26;
        readonly additive: true;
        readonly ftime: "0.15";
    }, {
        readonly element: "spiderdrop";
        readonly x: 59;
        readonly y: 17;
        readonly ftime: "0.08";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "lodgefire";
        readonly x: 100;
        readonly y: 40;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Waterpark Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "lobbyslide";
        readonly x: 54;
        readonly y: 26;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Tree Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "glow";
        readonly x: 30;
        readonly y: 21;
        readonly additive: true;
        readonly ftime: "0.155";
        readonly startframe: 3;
    }];
}, {
    readonly name: "Monster Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "monstercomp";
        readonly x: 96;
        readonly y: 34;
        readonly ftime: "0.05";
    }, {
        readonly element: "monsterholo";
        readonly x: 56;
        readonly y: 41;
        readonly additive: true;
        readonly ftime: "0.025";
    }];
}, {
    readonly name: "Holiday Lobby";
    readonly type: FloorType.Lobby;
    readonly holiday: "The Holidays";
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "xmaslobbytree";
        readonly x: 0;
        readonly y: 47;
        readonly ftime: "0.5";
    }, {
        readonly element: "xmaslobbylights";
        readonly x: 0;
        readonly y: 47;
        readonly ftime: "0.5";
    }];
}, {
    readonly name: "Corner Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Warren Buffet";
    readonly type: FloorType.Food;
    readonly stockVar: 220;
    readonly animations: readonly [{
        readonly element: "spookcandle";
        readonly x: 7;
        readonly y: 38;
        readonly additive: true;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Boxing Gym";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 221;
}, {
    readonly name: "Emperor Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Joey Bitton";
    readonly type: FloorType.Retail;
    readonly stockVar: 223;
}, {
    readonly name: "Penthouse Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "pentfire";
        readonly x: 85;
        readonly y: 43;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "College";
    readonly type: FloorType.Service;
    readonly stockVar: 225;
}, {
    readonly name: "Dance Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 226;
}, {
    readonly name: "Legit Watches";
    readonly type: FloorType.Retail;
    readonly stockVar: 227;
    readonly animations: readonly [{
        readonly element: "watch";
        readonly x: 65;
        readonly y: 24;
        readonly ftime: "1";
    }, {
        readonly element: "tvcar";
        readonly x: 9;
        readonly y: 20;
        readonly ftime: "0.2";
        readonly startframe: 5;
    }];
}, {
    readonly name: "Lotus House";
    readonly type: FloorType.Food;
    readonly stockVar: 228;
}, {
    readonly name: "Tiger Magic";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 229;
    readonly animations: readonly [{
        readonly element: "tigeranim";
        readonly x: 92;
        readonly y: 30;
        readonly ftime: "0.18";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Bubblesoak Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Pop Art Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Lodge Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "lodgefire";
        readonly x: 84;
        readonly y: 43;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Style Salon";
    readonly type: FloorType.Service;
    readonly stockVar: 233;
    readonly animations: readonly [{
        readonly element: "salonlights";
        readonly x: 8;
        readonly y: 7;
        readonly cyclecolor: "16";
        readonly additive: true;
    }];
}, {
    readonly name: "Superhero Lab";
    readonly type: FloorType.Creative;
    readonly stockVar: 234;
    readonly animations: readonly [{
        readonly element: "dna";
        readonly x: 61;
        readonly y: 33;
        readonly ftime: "0.25";
    }, {
        readonly element: "holo";
        readonly x: 7;
        readonly y: 33;
        readonly ftime: "0.1";
    }, {
        readonly element: "lcd";
        readonly x: 114;
        readonly y: 36;
        readonly ftime: "0.1";
    }, {
        readonly element: "globe";
        readonly x: 82;
        readonly y: 39;
        readonly ftime: "0.1";
        readonly additive: true;
    }];
}, {
    readonly name: "Native Art Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 235;
}, {
    readonly name: "Tailor";
    readonly type: FloorType.Service;
    readonly stockVar: 236;
}, {
    readonly name: "Moroccan Cuisine";
    readonly type: FloorType.Food;
    readonly stockVar: 237;
    readonly animations: readonly [{
        readonly element: "spookcandle";
        readonly x: 12;
        readonly y: 37;
        readonly additive: true;
        readonly ftime: "0.1";
    }, {
        readonly element: "spookcandle";
        readonly x: 118;
        readonly y: 37;
        readonly additive: true;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Candy Shoppe";
    readonly type: FloorType.Retail;
    readonly stockVar: 238;
    readonly stocktime: 30;
    readonly animations: readonly [{
        readonly element: "pole";
        readonly x: 27;
        readonly y: 41;
        readonly ftime: "0.2";
    }, {
        readonly element: "pole";
        readonly x: 50;
        readonly y: 41;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Wax Museum";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 239;
}, {
    readonly name: "Cupid Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "lodgefire";
        readonly x: 4;
        readonly y: 43;
        readonly ftime: "0.2";
    }, {
        readonly element: "bubblebath";
        readonly x: 106;
        readonly y: 40;
        readonly ftime: "0.2";
    }, {
        readonly element: "spookcandle";
        readonly x: 0;
        readonly y: 27;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 3;
    }, {
        readonly element: "spookcandle";
        readonly x: 17;
        readonly y: 27;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 5;
    }, {
        readonly element: "spookcandle";
        readonly x: 22;
        readonly y: 47;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 2;
    }, {
        readonly element: "spookcandle";
        readonly x: 119;
        readonly y: 47;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 4;
    }, {
        readonly element: "spookcandle";
        readonly x: 115;
        readonly y: 37;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 1;
    }];
}, {
    readonly name: "Groovy Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "waterlamp";
        readonly x: 54;
        readonly y: 45;
        readonly ftime: "0.25";
    }, {
        readonly element: "waterlamp";
        readonly x: 113;
        readonly y: 45;
        readonly ftime: "0.25";
        readonly startframe: 3;
    }];
}, {
    readonly name: "Island Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Rock Diner";
    readonly type: FloorType.Food;
    readonly stockVar: 243;
    readonly animations: readonly [{
        readonly element: "rockscreena";
        readonly x: 70;
        readonly y: 21;
        readonly ftime: "0.5";
    }, {
        readonly element: "rockscreenb";
        readonly x: 97;
        readonly y: 21;
        readonly ftime: "0.3";
    }, {
        readonly element: "rockscreenc";
        readonly x: 126;
        readonly y: 21;
        readonly ftime: "0.6";
    }];
}, {
    readonly name: "Bling Jewelers";
    readonly type: FloorType.Retail;
    readonly stockVar: 244;
    readonly stocktime: 60;
    readonly animations: readonly [{
        readonly element: "jewelstanda";
        readonly x: 56;
        readonly y: 30;
        readonly ftime: "0.2";
    }, {
        readonly element: "jewelstandb";
        readonly x: 112;
        readonly y: 30;
        readonly ftime: "0.2";
    }, {
        readonly element: "glint";
        readonly x: 7;
        readonly y: 15;
        readonly ftime: "0.1";
        readonly additive: true;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "glint";
        readonly x: 13;
        readonly y: 18;
        readonly ftime: "0.1";
        readonly additive: true;
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Creative Ink";
    readonly type: FloorType.Creative;
    readonly stockVar: 245;
    readonly animations: readonly [{
        readonly element: "ink";
        readonly x: 33;
        readonly y: 11;
        readonly ftime: "0.7";
    }, {
        readonly element: "fan";
        readonly x: 57;
        readonly y: 9;
        readonly ftime: "0.025";
    }];
}, {
    readonly name: "Device Repair";
    readonly type: FloorType.Service;
    readonly stockVar: 246;
    readonly animations: readonly [{
        readonly element: "bittv";
        readonly x: 2;
        readonly y: 20;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Splash Zone";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 247;
    readonly animations: readonly [{
        readonly element: "pool";
        readonly x: 78;
        readonly y: 45;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "Dragon Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "glow";
        readonly x: 5;
        readonly y: 31;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 2;
    }, {
        readonly element: "glow";
        readonly x: 87;
        readonly y: 31;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }];
}, {
    readonly name: "Contempo Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "moderntv";
        readonly x: 63;
        readonly y: 31;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Piano Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "pianofire";
        readonly x: 106;
        readonly y: 42;
        readonly ftime: "0.15";
    }, {
        readonly element: "spookcandle";
        readonly x: 70;
        readonly y: 18;
        readonly additive: true;
        readonly ftime: "0.13";
        readonly startframe: 3;
    }, {
        readonly element: "spookcandle";
        readonly x: 76;
        readonly y: 17;
        readonly additive: true;
        readonly ftime: "0.13";
        readonly startframe: 5;
    }, {
        readonly element: "spookcandle";
        readonly x: 82;
        readonly y: 18;
        readonly additive: true;
        readonly ftime: "0.13";
        readonly startframe: 2;
    }];
}, {
    readonly name: "Shrimp Buffet";
    readonly type: FloorType.Food;
    readonly stockVar: 251;
}, {
    readonly name: "Law Offices";
    readonly type: FloorType.Service;
    readonly stockVar: 252;
}, {
    readonly name: "Broadway Theatre";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 253;
}, {
    readonly name: "Tourist Trap";
    readonly type: FloorType.Retail;
    readonly stockVar: 254;
}, {
    readonly name: "Metal Studio";
    readonly type: FloorType.Creative;
    readonly stockVar: 255;
}, {
    readonly name: "Carmine Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Relax Apts.";
    readonly type: FloorType.Residential;
    readonly animations: readonly [{
        readonly element: "spookcandle";
        readonly x: 95;
        readonly y: 40;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 3;
        readonly frontlayer: 1;
    }, {
        readonly element: "spookcandle";
        readonly x: 48;
        readonly y: 47;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 5;
    }, {
        readonly element: "spookcandle";
        readonly x: 82;
        readonly y: 47;
        readonly additive: true;
        readonly ftime: "0.1";
        readonly startframe: 2;
    }];
}, {
    readonly name: "Regal Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Makerspace";
    readonly type: FloorType.Creative;
    readonly stockVar: 259;
}, {
    readonly name: "Indoor Skydiving";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 260;
}, {
    readonly name: "Burrito Bar";
    readonly type: FloorType.Food;
    readonly stockVar: 261;
}, {
    readonly name: "Brick Store";
    readonly type: FloorType.Retail;
    readonly stockVar: 262;
}, {
    readonly name: "BitBook";
    readonly type: FloorType.Service;
    readonly stockVar: 263;
}, {
    readonly name: "Springfield Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Camping Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Capsule Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Doggy Daycare";
    readonly type: FloorType.Service;
    readonly stockVar: 267;
}, {
    readonly name: "Skate Shop";
    readonly type: FloorType.Retail;
    readonly stockVar: 268;
}, {
    readonly name: "Cookie Shop";
    readonly type: FloorType.Food;
    readonly stockVar: 269;
}, {
    readonly name: "Space Museum";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 270;
}, {
    readonly name: "Model Trains";
    readonly type: FloorType.Creative;
    readonly stockVar: 271;
}, {
    readonly name: "Bitcraft Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Butterfly Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Cavern Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "Garage Apts.";
    readonly type: FloorType.Residential;
}, {
    readonly name: "VOTE! Lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Easter Lobby";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "bunnycounter";
        readonly x: 0;
        readonly y: 46;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor277grass";
        readonly x: 0;
        readonly y: 46;
        readonly ftime: "0.125";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Museum Lobby";
    readonly holiday: "Independence Day";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Celebration Lobby";
    readonly type: FloorType.Lobby;
    readonly holiday: "Independence Day";
    readonly character: "artmajor";
}, {
    readonly name: "Beach barbecue";
    readonly type: FloorType.Lobby;
    readonly holiday: "Summer";
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor280smoke";
        readonly x: 88;
        readonly y: 34;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Surfer paradise";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor281torch";
        readonly x: 60;
        readonly y: 37;
        readonly ftime: "0.125";
    }, {
        readonly element: "floor281surfer";
        readonly x: 73;
        readonly y: 48;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "torture chamber";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor282torch";
        readonly x: 13;
        readonly y: 28;
        readonly ftime: "0.07";
    }, {
        readonly element: "floor282cage";
        readonly x: 54;
        readonly y: 43;
        readonly ftime: "1.5";
    }];
}, {
    readonly name: "witch's chamber";
    readonly type: FloorType.Lobby;
    readonly holiday: "Halloween";
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor283pot";
        readonly x: 92;
        readonly y: 47;
        readonly ftime: "0.125";
    }, {
        readonly element: "floor283cat";
        readonly x: 117;
        readonly y: 47;
        readonly ftime: "1";
    }, {
        readonly element: "floor283spark";
        readonly x: 23;
        readonly y: 34;
        readonly ftime: "0.07";
    }, {
        readonly element: "floor283candle";
        readonly x: 9;
        readonly y: 9;
        readonly ftime: "0.5";
    }, {
        readonly element: "floor283book";
        readonly x: 74;
        readonly y: 31;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "christmas market";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
}, {
    readonly name: "santa claus office";
    readonly type: FloorType.Lobby;
    readonly holiday: "The Holidays";
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor285anim";
        readonly x: 47;
        readonly y: 47;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Legendary Lounge";
    readonly type: FloorType.VIPLounge;
    readonly animations: readonly [{
        readonly element: "floor286_star";
        readonly x: 7;
        readonly y: 35;
        readonly ftime: "0.125";
        readonly startdelay: "1.75";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor286_wall";
        readonly x: 54;
        readonly y: 46;
        readonly ftime: "0.125";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor286_aquarium";
        readonly x: 71;
        readonly y: 32;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Washington Crossing";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly hidden: true;
    readonly animations: readonly [{
        readonly element: "floor287_boat";
        readonly x: 70;
        readonly y: 45;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Ice Cream Parlor";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly hidden: true;
    readonly animations: readonly [{
        readonly element: "floor288_mixer";
        readonly x: 57;
        readonly y: 45;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Backdoor Icy Cart";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly holiday: "IceCream";
    readonly animations: readonly [{
        readonly element: "floor289_white";
        readonly x: 23;
        readonly y: 46;
        readonly ftime: "0.125";
    }, {
        readonly element: "floor289_black";
        readonly x: 98;
        readonly y: 38;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Tool Shed Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
    readonly animations: readonly [{
        readonly element: "floor290_tool";
        readonly x: 2;
        readonly y: 42;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Venice Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
    readonly animations: readonly [{
        readonly element: "floor291_boat";
        readonly x: 77;
        readonly y: 48;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Nordic Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
    readonly animations: readonly [{
        readonly element: "floor292_fire";
        readonly x: 74;
        readonly y: 41;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Spaceship Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
    readonly animations: readonly [{
        readonly element: "floor293_planets";
        readonly x: 65;
        readonly y: 48;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Friends Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
}, {
    readonly name: "Forever Frosty Bar";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor295_iceguy";
        readonly x: 35;
        readonly y: 46;
        readonly ftime: "0.07";
    }];
}, {
    readonly name: "Bone-chilling lobby";
    readonly holiday: "Halloween";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor296_torch_left";
        readonly x: 5;
        readonly y: 31;
        readonly ftime: "0.15";
    }, {
        readonly element: "floor296_torch_middle";
        readonly x: 53;
        readonly y: 43;
        readonly ftime: "0.15";
    }, {
        readonly element: "floor296_torch_right";
        readonly x: 103;
        readonly y: 30;
        readonly ftime: "0.15";
    }, {
        readonly element: "floor296_spark";
        readonly x: 110;
        readonly y: 36;
        readonly ftime: "0.125";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor296_diagonal_spark";
        readonly x: 104;
        readonly y: 36;
        readonly ftime: "0.125";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Dracula lobby";
    readonly holiday: "Halloween";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor297_picture_wink";
        readonly x: 78;
        readonly y: 20;
        readonly ftime: "0.2";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor297_eyes";
        readonly x: 20;
        readonly y: 7;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor297_eyes";
        readonly x: 102;
        readonly y: 7;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor297_eyes";
        readonly x: 116;
        readonly y: 6;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor297_eyes";
        readonly x: 41;
        readonly y: 44;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor297_eye";
        readonly x: 110;
        readonly y: 7;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor297_eye";
        readonly x: 19;
        readonly y: 31;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor297_pumpkin_glow";
        readonly x: 103;
        readonly y: 38;
        readonly ftime: "0.3";
        readonly additive: true;
    }, {
        readonly element: "floor297_glow";
        readonly x: 24;
        readonly y: 10;
        readonly ftime: "0.3";
        readonly additive: true;
    }, {
        readonly element: "floor297_chandelier";
        readonly x: 33;
        readonly y: 13;
        readonly ftime: "0.3";
    }];
}, {
    readonly name: "Eva hangar Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
}, {
    readonly name: "Scare Floor Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
}, {
    readonly name: "IT Department Apts.";
    readonly type: FloorType.Residential;
    readonly contentOffer: true;
}, {
    readonly name: "Ichiraku ramen";
    readonly type: FloorType.Food;
    readonly stockVar: 100;
    readonly contentOffer: true;
}, {
    readonly name: "Crabbyland";
    readonly type: FloorType.Entertainment;
    readonly stockVar: 122;
    readonly contentOffer: true;
}, {
    readonly name: "Budokai arena";
    readonly type: FloorType.Service;
    readonly stockVar: 108;
    readonly contentOffer: true;
}, {
    readonly name: "Pilgrims household lobby";
    readonly holiday: "Thanksgiving";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor304_cat";
        readonly x: 61;
        readonly y: 30;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Pilgrims cabin lobby";
    readonly holiday: "Thanksgiving";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor305_ropes";
        readonly x: 9;
        readonly y: 17;
        readonly ftime: "0.3";
    }, {
        readonly element: "floor305_water";
        readonly x: 69;
        readonly y: 24;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Christmas lobby";
    readonly holiday: "The Holidays";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor306_window";
        readonly x: 0;
        readonly y: 30;
        readonly ftime: "0.125";
    }, {
        readonly element: "floor306_candle";
        readonly x: 119;
        readonly y: 30;
        readonly ftime: "0.125";
    }, {
        readonly element: "floor306_tree";
        readonly x: 89;
        readonly y: 44;
        readonly ftime: "0.45";
    }];
}, {
    readonly name: "Christmas toy store";
    readonly type: FloorType.Retail;
    readonly stockVar: 77;
    readonly animations: readonly [{
        readonly element: "floor307_anim";
        readonly x: 69;
        readonly y: 45;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Grumpy Lair Lobby";
    readonly holiday: "The Holidays";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor308_gas";
        readonly x: 5;
        readonly y: 19;
        readonly ftime: "0.3";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "floor308_anim";
        readonly x: 74;
        readonly y: 44;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Hobbit lobby";
    readonly type: FloorType.Lobby;
    readonly hidden: true;
    readonly character: "artmajor";
    readonly animations: readonly [{
        readonly element: "floor309_door";
        readonly x: 73;
        readonly y: 44;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Forest burrow lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Choco hopper lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
}, {
    readonly name: "Art eggway lobby";
    readonly type: FloorType.Lobby;
    readonly character: "artmajor";
    readonly hidden: true;
    readonly animations: readonly [{
        readonly element: "floor312_light";
        readonly x: 79;
        readonly y: 30;
        readonly ftime: "0.2";
    }, {
        readonly element: "floor312_cogs";
        readonly x: 93;
        readonly y: 41;
        readonly ftime: "0.125";
    }, {
        readonly element: "floor312_stick";
        readonly x: 81;
        readonly y: 27;
        readonly ftime: "0.25";
    }, {
        readonly element: "floor312_eggs";
        readonly x: 92;
        readonly y: 34;
        readonly ftime: "0.125";
    }];
}];
export type Floor = (typeof floors)[number];
//# sourceMappingURL=floors.d.ts.map