/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-pet-data.js
 *
 * With TinyTower version: 4.29.0
 *
 * On: Tue, 21 Nov 2023 19:22:26 GMT
 */

export const pets = {} as const;
export type Pet = typeof pets;
