/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-pet-data.js
 *
 * With TinyTower version: 5.2.1
 *
 * On: Tue, 07 May 2024 21:13:28 GMT
 */

export const pets = {} as const;
export type Pet = typeof pets;
