/**
 * This file was auto-generated by a frida agent
 *
 * Generated by:
 * /workspaces/tinyburg/packages/insight/dist/src/agents/get-roof-data.js
 *
 * With TinyTower version: 5.2.1
 *
 * On: Wed, 08 May 2024 23:07:21 GMT
 */
export declare const numberOfRoofs: 79;
export declare const roofs: readonly [{
    readonly name: "Crane";
    readonly fwcolors: readonly [];
}, {
    readonly name: "Blimp Port";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "blimplight";
        readonly x: 20;
        readonly y: 16;
        readonly ftime: "1";
    }, {
        readonly element: "blimplight";
        readonly x: 3;
        readonly y: 60;
        readonly ftime: "1";
    }, {
        readonly element: "blimplight";
        readonly x: 73;
        readonly y: 60;
        readonly ftime: "1";
    }, {
        readonly element: "blimplight";
        readonly x: 150;
        readonly y: 60;
        readonly ftime: "1";
    }, {
        readonly element: "blimp";
        readonly x: 26;
        readonly y: 48;
        readonly ftime: "1";
    }, {
        readonly element: "bitblinkb";
        readonly x: 63;
        readonly y: 79;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bitblinkb";
        readonly x: 77;
        readonly y: 79;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bitblinkc";
        readonly x: 108;
        readonly y: 79;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bitblinkb";
        readonly x: 128;
        readonly y: 79;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Pyramid";
    readonly fwcolors: readonly [];
}, {
    readonly name: "Scream Tower";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "blimplight";
        readonly x: 75;
        readonly y: 16;
        readonly ftime: "1";
    }, {
        readonly element: "towerlighta";
        readonly x: 60;
        readonly y: 24;
        readonly ftime: "0.25";
        readonly startframe: 1;
    }, {
        readonly element: "towerlighta";
        readonly x: 70;
        readonly y: 24;
        readonly ftime: "0.25";
        readonly startframe: 2;
    }, {
        readonly element: "towerlighta";
        readonly x: 80;
        readonly y: 24;
        readonly ftime: "0.25";
        readonly startframe: 1;
    }, {
        readonly element: "towerlighta";
        readonly x: 90;
        readonly y: 24;
        readonly ftime: "0.25";
        readonly startframe: 2;
    }, {
        readonly element: "towerlighta";
        readonly x: 98;
        readonly y: 24;
        readonly ftime: "0.25";
        readonly startframe: 1;
    }, {
        readonly element: "towerlighta";
        readonly x: 103;
        readonly y: 24;
        readonly ftime: "0.25";
        readonly startframe: 2;
    }, {
        readonly element: "towerlightb";
        readonly x: 59;
        readonly y: 225;
        readonly ftime: "0.15";
        readonly startframe: 6;
    }, {
        readonly element: "towerlightb";
        readonly x: 59;
        readonly y: 192;
        readonly ftime: "0.15";
        readonly startframe: 5;
    }, {
        readonly element: "towerlightb";
        readonly x: 59;
        readonly y: 160;
        readonly ftime: "0.15";
        readonly startframe: 4;
    }, {
        readonly element: "towerlightb";
        readonly x: 59;
        readonly y: 127;
        readonly ftime: "0.15";
        readonly startframe: 3;
    }, {
        readonly element: "towerlightb";
        readonly x: 59;
        readonly y: 95;
        readonly ftime: "0.15";
        readonly startframe: 2;
    }, {
        readonly element: "towerlightb";
        readonly x: 59;
        readonly y: 62;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }, {
        readonly element: "towerlightb";
        readonly x: 96;
        readonly y: 225;
        readonly ftime: "0.15";
        readonly startframe: 6;
    }, {
        readonly element: "towerlightb";
        readonly x: 96;
        readonly y: 192;
        readonly ftime: "0.15";
        readonly startframe: 5;
    }, {
        readonly element: "towerlightb";
        readonly x: 96;
        readonly y: 160;
        readonly ftime: "0.15";
        readonly startframe: 4;
    }, {
        readonly element: "towerlightb";
        readonly x: 96;
        readonly y: 127;
        readonly ftime: "0.15";
        readonly startframe: 3;
    }, {
        readonly element: "towerlightb";
        readonly x: 96;
        readonly y: 95;
        readonly ftime: "0.15";
        readonly startframe: 2;
    }, {
        readonly element: "towerlightb";
        readonly x: 96;
        readonly y: 62;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }, {
        readonly element: "towerlightb";
        readonly x: 103;
        readonly y: 225;
        readonly ftime: "0.15";
        readonly startframe: 6;
    }, {
        readonly element: "towerlightb";
        readonly x: 103;
        readonly y: 192;
        readonly ftime: "0.15";
        readonly startframe: 5;
    }, {
        readonly element: "towerlightb";
        readonly x: 103;
        readonly y: 160;
        readonly ftime: "0.15";
        readonly startframe: 4;
    }, {
        readonly element: "towerlightb";
        readonly x: 103;
        readonly y: 127;
        readonly ftime: "0.15";
        readonly startframe: 3;
    }, {
        readonly element: "towerlightb";
        readonly x: 103;
        readonly y: 95;
        readonly ftime: "0.15";
        readonly startframe: 2;
    }, {
        readonly element: "towerlightb";
        readonly x: 103;
        readonly y: 62;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }, {
        readonly element: "towerdropa";
        readonly x: 59;
        readonly y: 249;
        readonly ftime: "0.05";
    }];
}, {
    readonly name: "Eiffel Tower";
    readonly fwcolors: readonly [];
}, {
    readonly name: "Bit Rock";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "rocksign";
        readonly x: 30;
        readonly y: 103;
        readonly ftime: "0.5";
    }, {
        readonly element: "speaker";
        readonly x: 117;
        readonly y: 32;
        readonly ftime: "0.15";
    }, {
        readonly element: "speaker";
        readonly x: 50;
        readonly y: 32;
        readonly ftime: "0.15";
    }, {
        readonly element: "rockarm";
        readonly x: 108;
        readonly y: 52;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockpiano";
        readonly x: 61;
        readonly y: 51;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockerc";
        readonly x: 75;
        readonly y: 46;
        readonly ftime: "0.1";
    }, {
        readonly element: "rockerhead";
        readonly x: 84;
        readonly y: 46;
        readonly ftime: "0.5";
    }, {
        readonly element: "rockmouth";
        readonly x: 85;
        readonly y: 49;
        readonly ftime: "0.38";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockblue";
        readonly x: 66;
        readonly y: 53;
        readonly ftime: "2";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
        readonly additive: true;
    }, {
        readonly element: "rockyellow";
        readonly x: 57;
        readonly y: 53;
        readonly ftime: "2";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
        readonly additive: true;
    }, {
        readonly element: "rockred";
        readonly x: 48;
        readonly y: 53;
        readonly ftime: "2";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
        readonly additive: true;
    }, {
        readonly element: "rockcrowda";
        readonly x: 156;
        readonly y: 48;
        readonly ftime: "0.5";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockcrowdb";
        readonly x: 143;
        readonly y: 56;
        readonly ftime: "0.5";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockcrowdc";
        readonly x: 128;
        readonly y: 64;
        readonly ftime: "0.5";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockcrowdd";
        readonly x: 10;
        readonly y: 48;
        readonly ftime: "0.5";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockcrowde";
        readonly x: 23;
        readonly y: 56;
        readonly ftime: "0.5";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "rockcrowdf";
        readonly x: 36;
        readonly y: 64;
        readonly ftime: "0.5";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Android";
    readonly platform: "android";
    readonly fwcolors: readonly [];
}, {
    readonly name: "Mapple Cube";
    readonly platform: "iphoneplayer";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "bitblinkh";
        readonly x: 32;
        readonly y: 193;
        readonly ftime: "0.25";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bityawnd";
        readonly x: 32;
        readonly y: 196;
        readonly ftime: "1";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bitblinkd";
        readonly x: 130;
        readonly y: 143;
        readonly ftime: "0.25";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "New York";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "redlight";
        readonly x: 93;
        readonly y: 75;
        readonly ftime: "1";
    }, {
        readonly element: "redlight";
        readonly x: 136;
        readonly y: 0;
        readonly ftime: "1";
        readonly startframe: 2;
    }];
}, {
    readonly name: "Fun Fair";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "fair";
        readonly x: 0;
        readonly y: 252;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Pocket Plane";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "propeller";
        readonly x: 62;
        readonly y: 7;
        readonly ftime: "0.02";
    }, {
        readonly element: "propellerb";
        readonly x: 2;
        readonly y: 16;
        readonly ftime: "0.02";
    }, {
        readonly element: "bityawnb";
        readonly x: 63;
        readonly y: 41;
        readonly ftime: "1";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bitblinkd";
        readonly x: 63;
        readonly y: 38;
        readonly ftime: "0.25";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bitblinkg";
        readonly x: 75;
        readonly y: 38;
        readonly ftime: "0.25";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blimplight";
        readonly x: 6;
        readonly y: 77;
        readonly ftime: "1";
    }, {
        readonly element: "blimplight";
        readonly x: 144;
        readonly y: 77;
        readonly ftime: "1";
    }];
}, {
    readonly name: "Pocket Train";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "bitblinkd";
        readonly x: 89;
        readonly y: 89;
        readonly ftime: "0.25";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "China";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "glow";
        readonly x: 2;
        readonly y: 156;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 3;
    }, {
        readonly element: "glow";
        readonly x: 148;
        readonly y: 156;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }];
}, {
    readonly name: "Europe";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "eurolite";
        readonly x: 24;
        readonly y: 5;
        readonly additive: true;
        readonly ftime: "1";
        readonly startframe: 1;
    }, {
        readonly element: "eurolite";
        readonly x: 129;
        readonly y: 5;
        readonly additive: true;
        readonly ftime: "1";
        readonly startframe: 2;
    }, {
        readonly element: "eurowin";
        readonly x: 44;
        readonly y: 112;
        readonly ftime: "0.06";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "spotlights";
        readonly x: 0;
        readonly y: 134;
        readonly ftime: "0.5";
    }];
}, {
    readonly name: "Russia";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "ruslite";
        readonly x: 42;
        readonly y: 112;
        readonly additive: true;
        readonly ftime: "1";
        readonly startframe: 1;
    }, {
        readonly element: "ruslite";
        readonly x: 136;
        readonly y: 112;
        readonly additive: true;
        readonly ftime: "1";
        readonly xscale: -1;
        readonly startframe: 1;
    }];
}, {
    readonly name: "NASA";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "shuttlea";
        readonly x: 30;
        readonly y: 162;
        readonly ftime: "1.25";
    }, {
        readonly element: "shuttleb";
        readonly x: 131;
        readonly y: 165;
        readonly ftime: "1.25";
    }, {
        readonly element: "shuttlec";
        readonly x: 15;
        readonly y: 344;
        readonly ftime: "1.25";
    }, {
        readonly element: "shuttled";
        readonly x: 138;
        readonly y: 346;
        readonly ftime: "1.25";
    }];
}, {
    readonly name: "Farm";
    readonly fwcolors: readonly [];
}, {
    readonly name: "Desert Island";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "water";
        readonly x: 0;
        readonly y: 149;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "Disco Zoo";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "rainbow";
        readonly x: 32;
        readonly y: 194;
        readonly ftime: "0.5";
    }, {
        readonly element: "zoo";
        readonly x: 30;
        readonly y: 173;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "UFO";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "ufo";
        readonly x: 0;
        readonly y: 8;
        readonly frontlayer: 1;
        readonly ftime: "0.5";
    }];
}, {
    readonly name: "British";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "jack";
        readonly x: 117;
        readonly y: 51;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Arc de Triomphe";
    readonly fwcolors: readonly [];
}, {
    readonly name: "Roman";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "romewater";
        readonly x: 69;
        readonly y: 201;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Taj Mahal";
    readonly fwcolors: readonly [];
}, {
    readonly name: "Spooky";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roofwindow";
        readonly x: 19;
        readonly y: 174;
        readonly ftime: "0.1";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Neon Sign";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "neonguy";
        readonly x: 2;
        readonly y: 109;
        readonly ftime: "0.3";
    }, {
        readonly element: "neontiny";
        readonly x: 35;
        readonly y: 107;
        readonly ftime: "0.6";
    }, {
        readonly element: "neonglass";
        readonly x: 139;
        readonly y: 60;
        readonly ftime: "1.2";
    }, {
        readonly element: "neonspot";
        readonly x: -22;
        readonly y: 107;
        readonly additive: true;
    }];
}, {
    readonly name: "Galleon";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "blackflag";
        readonly x: 86;
        readonly y: 52;
        readonly ftime: "0.2";
    }, {
        readonly element: "pshield";
        readonly x: 78;
        readonly y: 122;
        readonly ftime: "0.08";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "pglass";
        readonly x: 24;
        readonly y: 181;
        readonly ftime: "0.05";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }, {
        readonly element: "glow";
        readonly x: 7;
        readonly y: 137;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 3;
    }, {
        readonly element: "glow";
        readonly x: 135;
        readonly y: 137;
        readonly additive: true;
        readonly ftime: "0.15";
        readonly startframe: 1;
    }];
}, {
    readonly name: "Statue";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "statueglint";
        readonly x: 23;
        readonly y: 175;
        readonly ftime: "0.05";
        readonly frontlayer: 1;
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Greek Temple";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "greektorcha";
        readonly x: 36;
        readonly y: 158;
        readonly ftime: "0.15";
    }, {
        readonly element: "greektorchb";
        readonly x: 128;
        readonly y: 159;
        readonly ftime: "0.15";
    }, {
        readonly element: "glitter";
        readonly x: 8;
        readonly y: 46;
        readonly ftime: "0.15";
        readonly additive: true;
    }];
}, {
    readonly name: "Jungle Temple";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "blinkeye";
        readonly x: 70;
        readonly y: 154;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blinkeye";
        readonly x: 72;
        readonly y: 143;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blinkeye";
        readonly x: 81;
        readonly y: 151;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blinkeye";
        readonly x: 85;
        readonly y: 146;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blinkeye";
        readonly x: 90;
        readonly y: 139;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "blinkeye";
        readonly x: 90;
        readonly y: 158;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Fantasy Castle";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof30flags";
        readonly x: 0;
        readonly y: 270;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Secret Lab";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof31anim";
        readonly x: 0;
        readonly y: 230;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Dojo";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Halloween";
    readonly holiday: "Halloween";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof33glow";
        readonly x: 33;
        readonly y: 178;
        readonly ftime: "0.2";
        readonly additive: true;
    }];
}, {
    readonly name: "Waterpark";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "watertube";
        readonly x: 43;
        readonly y: 68;
        readonly ftime: "0.15";
    }, {
        readonly element: "watertube";
        readonly x: 43;
        readonly y: 105;
        readonly ftime: "0.12";
    }, {
        readonly element: "waterspill";
        readonly x: 55;
        readonly y: 138;
        readonly ftime: "0.12";
    }, {
        readonly element: "slideguy";
        readonly x: 44;
        readonly y: 136;
        readonly ftime: "0.1";
    }, {
        readonly element: "slidelines";
        readonly x: 41;
        readonly y: 129;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Tree";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "glow";
        readonly x: 65;
        readonly y: 72;
        readonly additive: true;
        readonly ftime: "0.155";
        readonly startframe: 3;
    }, {
        readonly element: "glow";
        readonly x: 131;
        readonly y: 96;
        readonly additive: true;
        readonly ftime: "0.152";
        readonly startframe: 2;
    }, {
        readonly element: "glow";
        readonly x: 48;
        readonly y: 125;
        readonly additive: true;
        readonly ftime: "0.151";
        readonly startframe: 1;
    }, {
        readonly element: "glow";
        readonly x: 24;
        readonly y: 163;
        readonly additive: true;
        readonly ftime: "0.156";
        readonly startframe: 3;
    }, {
        readonly element: "glow";
        readonly x: 106;
        readonly y: 148;
        readonly additive: true;
        readonly ftime: "0.157";
        readonly startframe: 2;
    }, {
        readonly element: "glow";
        readonly x: 132;
        readonly y: 160;
        readonly additive: true;
        readonly ftime: "0.158";
        readonly startframe: 1;
    }];
}, {
    readonly name: "Monster";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof36anim";
        readonly x: 0;
        readonly y: 173;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Snowman Roof";
    readonly holiday: "The Holidays";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Snowy Roof";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Historic Roof";
    readonly platform: "historic";
    readonly fwcolors: readonly [];
}, {
    readonly name: "American Flag Roof";
    readonly holiday: "Independence Day";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "amflag";
        readonly x: 59;
        readonly y: 78;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Forest";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Easter Roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof42anim";
        readonly x: 0;
        readonly y: 74;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Capitol Roof";
    readonly holiday: "Independence Day";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "4th of July Balloons Roof";
    readonly holiday: "Independence Day";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Drive-in cinema";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof45anim";
        readonly x: 0;
        readonly y: 71;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Party yacht";
    readonly holiday: "Summer";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof46anim";
        readonly x: 0;
        readonly y: 71;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "mysterious castle";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof47anim";
        readonly x: 0;
        readonly y: 107;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "dark forest";
    readonly holiday: "Halloween";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "house";
        readonly x: 63;
        readonly y: 65;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "ski resort";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof49anim";
        readonly x: 0;
        readonly y: 80;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "christmas tree";
    readonly holiday: "The Holidays";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "reindeer";
        readonly x: 0;
        readonly y: 92;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Monster Truck Arena";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "truck";
        readonly x: 67;
        readonly y: 89;
        readonly ftime: "0.15";
    }, {
        readonly element: "star";
        readonly x: 40;
        readonly y: 36;
        readonly ftime: "0.06";
    }];
}, {
    readonly name: "Bit cream bar";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "icecream";
        readonly x: 82;
        readonly y: 48;
        readonly ftime: "0.06";
    }, {
        readonly element: "title";
        readonly x: 114;
        readonly y: 49;
        readonly ftime: "0.25";
    }, {
        readonly element: "soundbox";
        readonly x: 154;
        readonly y: 72;
        readonly ftime: "0.1";
    }, {
        readonly element: "sunshield";
        readonly x: 89;
        readonly y: 75;
        readonly ftime: "0.1";
    }, {
        readonly element: "garland";
        readonly x: 7;
        readonly y: 49;
        readonly ftime: "0.06";
    }, {
        readonly element: "blueumbrela";
        readonly x: 49;
        readonly y: 59;
        readonly ftime: "0.1";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "pinkumbrela";
        readonly x: 13;
        readonly y: 59;
        readonly ftime: "0.1";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Tiny ice factory";
    readonly holiday: "IceCream";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "machine";
        readonly x: 1;
        readonly y: 95;
        readonly ftime: "0.05";
    }];
}, {
    readonly name: "Flyboard Acrobatics";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "surfer";
        readonly x: 55;
        readonly y: 88;
        readonly ftime: "0.07";
    }, {
        readonly element: "boats";
        readonly x: 1;
        readonly y: 82;
        readonly ftime: "0.14";
    }];
}, {
    readonly name: "Dollhouse roof";
    readonly contentOffer: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Hobitizen";
    readonly contentOffer: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Jack-o-lantern roof";
    readonly holiday: "Halloween";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof57anim";
        readonly additive: true;
        readonly x: 55;
        readonly y: 89;
        readonly ftime: "0.2";
    }];
}, {
    readonly name: "Haunted roof";
    readonly holiday: "Halloween";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "haunted_house";
        readonly x: 50;
        readonly y: 89;
        readonly ftime: "0.125";
    }, {
        readonly element: "eyes";
        readonly x: 21;
        readonly y: 97;
        readonly ftime: "0.25";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "eyes";
        readonly x: 139;
        readonly y: 98;
        readonly ftime: "0.175";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "mouse";
        readonly x: 85;
        readonly y: 115;
        readonly ftime: "0.2";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "bats";
        readonly x: 80;
        readonly y: 43;
        readonly ftime: "0.15";
        readonly loopdelay: readonly [];
    }];
}, {
    readonly name: "Cornucopia";
    readonly holiday: "Thanksgiving";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Mayflower";
    readonly holiday: "Thanksgiving";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "ship";
        readonly x: 10;
        readonly y: 57;
        readonly ftime: "0.125";
    }, {
        readonly element: "backwave";
        readonly x: 0;
        readonly y: 57;
        readonly ftime: "0.25";
    }, {
        readonly element: "frontwave";
        readonly x: 0;
        readonly y: 57;
        readonly ftime: "0.25";
        readonly startframe: 3;
    }];
}, {
    readonly name: "Snow village roof";
    readonly holiday: "The Holidays";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof61anim";
        readonly x: 0;
        readonly y: 121;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "Snow globe roof";
    readonly holiday: "The Holidays";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof62snow";
        readonly x: 70;
        readonly y: 50;
        readonly ftime: "0.25";
    }, {
        readonly element: "roof62star";
        readonly x: 105;
        readonly y: 42;
        readonly ftime: "0.15";
    }, {
        readonly element: "roof62tree";
        readonly x: 98;
        readonly y: 89;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "Ho ho ho roof";
    readonly holiday: "The Holidays";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "roof63_santa";
        readonly x: 4;
        readonly y: -1;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "2024 dragon roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Dragon roof";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Green dragon roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "eye";
        readonly x: 52;
        readonly y: 46;
        readonly ftime: "0.15";
    }, {
        readonly element: "embers";
        readonly x: 18;
        readonly y: 52;
        readonly ftime: "0.15";
    }, {
        readonly element: "dragon_ball";
        readonly x: 50;
        readonly y: 96;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Heartfelt Teddy";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "heart";
        readonly x: 35;
        readonly y: 100;
        readonly ftime: "0.25";
    }, {
        readonly element: "heart";
        readonly x: 20;
        readonly y: 90;
        readonly ftime: "0.15";
    }, {
        readonly element: "heart";
        readonly x: 135;
        readonly y: 85;
        readonly ftime: "0.25";
    }, {
        readonly element: "heart";
        readonly x: 120;
        readonly y: 80;
        readonly ftime: "0.15";
    }];
}, {
    readonly name: "Moonlit Love Embrace";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "hearts";
        readonly x: 80;
        readonly y: 100;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "Love hearts roof";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Pot of Gold Rainbow Roof";
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "pot";
        readonly x: 3;
        readonly y: 52;
        readonly ftime: "0.075";
    }];
}, {
    readonly name: "Leprechaun meadows roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "frame_";
        readonly x: 10;
        readonly y: 82;
        readonly ftime: "0.1";
    }];
}, {
    readonly name: "Rabbit statue roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "bunny_";
        readonly x: 100;
        readonly y: 110;
        readonly ftime: "0.25";
    }];
}, {
    readonly name: "Chubby bunny roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Egg nest roof";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "'Tiny' worm roof";
    readonly fwcolors: readonly [];
    readonly contentOffer: true;
    readonly animations: readonly [{
        readonly element: "anim";
        readonly x: 32;
        readonly y: 141;
        readonly ftime: "0.125";
    }];
}, {
    readonly name: "Majestic Roots Roof";
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Froggy Stump Roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [];
}, {
    readonly name: "Sakura Gate Roof";
    readonly hidden: true;
    readonly fwcolors: readonly [];
    readonly animations: readonly [{
        readonly element: "leafs";
        readonly x: 90;
        readonly y: 150;
        readonly ftime: "0.125";
    }, {
        readonly element: "leafs";
        readonly x: 85;
        readonly y: 145;
        readonly ftime: "0.125";
        readonly loopdelay: readonly [];
    }, {
        readonly element: "leafs";
        readonly x: 80;
        readonly y: 155;
        readonly ftime: "0.125";
        readonly loopdelay: readonly [];
    }];
}];
export type Roof = (typeof roofs)[number];
//# sourceMappingURL=roofs.d.ts.map