/**
 * @since 1.0.0
 * @category Elevators
 */

//////////////////////////////////////////////////////////////////

/**
 * This file was auto-generated by a frida agent.
 *
 * Generated On: Thu, 05 Feb 2026 16:10:36 GMT
 *
 * With Tiny Tower Version: 7.3.0
 */

export const elevators = [
    "Trusty Rusty",
    "Steel Series SE",
    "Pullman Prestige",
    "Litestripe 3000",
    "Disco Lift",
    "Egyptian Lift",
    "NB200 Commercial Lift",
    "Insta-Lift 200 SE",
    "Ultra-Lift 3000 Extreme",
    "Infini-lift lightspeed",
    "Glass Lift",
    "Police Box",
    "Metal Cage",
    "Halloween Lift",
    "Holiday Lift",
    "Marble Lift",
    "Hydro Lift",
    "Tree Lift",
    "Easter Lift",
    "Independence Lift",
    "Liberty Lift",
    "Pineapple",
    "Jungle",
    "pumpkin cage",
    "iron maiden",
    "green present",
    "ski lift",
    "Elevator of Freedom",
    "Cooling Elevator",
    "Ice Cream",
    "Lifeguard",
    "Grim elevator",
    "Coffin elevator",
    "Pilgrims elevator",
    "Pumpkin elevator",
    "Jingle bells elevator",
    "North pole elevator",
    "Heart elevator",
    "Leprechaun beverage elevator",
    "St. Patrick's hat elevator",
    "Bunny hop elevator",
    "Egg basket elevator",
    "Blossom Tree Elevator",
    "Bloom Elevator",
    "Ice Cream Shop Elevator",
    "Ice Cream Fridge Elevator",
    "Washington Elevator",
    "Discobol Elevator",
    "Metal Titan Elevator",
    "Beach Sandal Elevator",
    "Flamingo Elevator",
    "Synthwave Elevator",
    "Watermelon Elevator",
    "Pineapple Elevator",
    "Eggplant Elevator",
    "Cthulu Elevator",
    "Frank Elevator",
    "Greenskull Elevator",
    "Autumn elevator",
    "Drumstick",
    "Gift",
    "Nutcracker",
    "Crystal Celebration",
    "Crypto Coaster",
    "Golden Snake Elevator",
    "Wave Elevator",
    "Love Mail Elevator",
    "Fairy Elevator",
    "Emerald Lyre Elevator",
    "Egg Nest Elevator",
    "Monster Creep Elevator",
    "Diamond Mine Elevator",
    "Sprinkle Elevator",
    "Ice Chocolate Elevator",
    "Sweet Spot Elevator",
    "4th of July Elevator",
    "Log Cabin Elevator",
    "Barn Elevator",
    "Windmill elevator",
    "Oven Elevator",
    "Snowman Elevator",
] as const;

export type Elevator = (typeof elevators)[number];

//////////////////////////////////////////////////////////////////
