name: Reusable rush build workflow

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      KNOWN_HOSTS:
        required: true
      TS_OAUTH_SECRET:
        required: true
      TS_OAUTH_CLIENT_ID:
        required: true

jobs:
  build-packages:
    strategy:
      matrix:
        include:
          - NodeVersion: 14
            OS: ubuntu-latest
          - NodeVersion: 18
            OS: ubuntu-latest
    name: Node.js v${{ matrix.NodeVersion }} (${{ matrix.OS }})
    runs-on: ${{ matrix.OS }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Testing Server Online?
        run: |
          tailscale status
        # tailscale ping ci.internal.tinyburg.app

      - name: Start ssh agent
        run: |
          eval "$(ssh-agent -s)"
          echo $SSH_AUTH_SOCK
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Add SSH key to agent
        run: |
          echo $SSH_AUTH_SOCK
          ssh-add -D
          ssh-add

      # - name: Testing Server Reachable?
      #   run: ssh ci@ci.internal.tinyburg.app "echo 'Hi, Mom!'"

      - if: runner.os == 'Linux'
        name: Start xvfb
        run: |
          sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: common/temp/build-cache
          key: ${{ runner.os }}_node-${{ matrix.NodeVersion }}_build-cache

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: |
          node common/scripts/install-run-rush.js install
          node common/scripts/install-run-rush.js update-autoinstaller --name rush-prettier
          node common/scripts/install-run-rush.js update-autoinstaller --name rush-commitlint

      - name: Rush build and test
        run: |
          node common/scripts/install-run-rush.js rebuild
        # node common/scripts/install-run-rush.js test --timeline --production
        env:
          RUSH_BUILD_CACHE_ENABLED: 1
          RUSH_BUILD_CACHE_WRITE_ALLOWED: 1
          ARCHITECT_DOCKER_HOST: "ssh://ci@ci.internal.tinyburg.app:22"
