name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Node.js v${{ matrix.NodeVersion }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        NodeVersion: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Testing Server Online?
        run: |
          tailscale status
          tailscale ping skynet.internal.leoconforti.us

      - name: Start ssh agent
        run: |
          eval "$(ssh-agent -s)"
          echo $SSH_AUTH_SOCK
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Add SSH key to agent
        run: |
          echo $SSH_AUTH_SOCK
          ssh-add -D
          ssh-add

      - name: Testing Server Reachable?
        run: ssh root@skynet.internal.leoconforti.us "echo 'Hi, Mom!'"

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: |
          node common/scripts/install-run-rush.js install
          node common/scripts/install-run-rush.js update-autoinstaller --name rush-prettier
          node common/scripts/install-run-rush.js update-autoinstaller --name rush-commitlint
          (cd packages/apks/vendor && ./setup.sh)
          (cd packages/architect/jwt-provider && ./setup.sh)

      - name: Rush test
        run: node common/scripts/install-run-rush.js retest --timeline --production
        env:
          ARCHITECT_DATA_DIRECTORY: "/mnt/disks/TrueNAS_iSCSI_Disk/"
          ARCHITECT_DOCKER_HOST: "ssh://root@skynet.internal.leoconforti.us:22"
