name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Node.js v${{ matrix.NodeVersion }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NodeVersion: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush test
        run: node common/scripts/install-run-rush.js test --verbose --timeline --production
