name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-rush.yaml
    secrets: inherit

  # build-docker-authproxy:
  #   needs: build
  #   uses: ./.github/workflows/build-rush.yaml
  #   secrets: inherit
  #   with:
  #     buildParameters: --verbose

  # build-docker-auto-gold-bits:
  #   needs: build
  #   uses: ./.github/workflows/build-rush.yaml
  #   secrets: inherit
  #   with:
  #     buildParameters: --verbose

  # build-docker-discord-bot:
  #   needs: build
  #   uses: ./.github/workflows/build-rush.yaml
  #   secrets: inherit
  #   with:
  #     buildParameters: --verbose
