name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  rush-build:
    name: "Rush build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/workflows/rush-build

  rush-publish:
    needs: rush-build
    name: "Rush publish"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi, mom!"

  docker-authproxy:
    needs: rush-build
    name: "Docker authproxy build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/workflows/docker-build
        with:
          PROJECT: "@tinyburg/authproxy"
          DOCKERFILE: "./apps/authproxy/Dockerfile"

  docker-auto-gold-bits:
    needs: rush-build
    name: "Docker auto gold bits build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/workflows/docker-build
        with:
          PROJECT: "auto-gold-bits"
          DOCKERFILE: "./apps/auto-gold-bits/Dockerfile"
