name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  rush-build:
    name: "Rush build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/composable-workflows/rush-build
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}

  rush-publish:
    needs: rush-build
    name: "Rush publish"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi, mom!"

  docker-authproxy:
    name: "Docker authproxy build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/composable-workflows/rush-build
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      - uses: ./.github/composable-workflows/docker-build
        with:
          PROJECT: "@tinyburg/authproxy"
          DOCKERFILE: "./apps/authproxy/Dockerfile"
          TAG: "ghcr.io/leonitousconforti/tinyburg/authproxy:latest"
