name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/build.yaml

  deploy-authproxy:
    needs: build
    runs-on: ubuntu-latest

  deploy-auto-gold-bits:
    needs: build
    runs-on: ubuntu-latest

  deploy-discord-bot:
    needs: build
    runs-on: ubuntu-latest

  deploy-repl-demo:
    needs: build
    runs-on: ubuntu-latest
