name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  rush-build:
    name: "Rush build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/workflows/rush-build
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}

  rush-publish:
    needs: rush-build
    name: "Rush publish"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi, mom!"

  docker-authproxy:
    needs: rush-build
    name: "Docker authproxy build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/workflows/rush-build
        with:
          BUILD_PARAMETERS: "--to @tinyburg/authproxy"
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      - uses: ./.github/workflows/docker-build
        with:
          PROJECT: "authproxy"
          DOCKERFILE: "./apps/authproxy/Dockerfile"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-auto-gold-bits:
    needs: rush-build
    name: "Docker auto-gold-bits build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ./.github/workflows/rush-build
        with:
          BUILD_PARAMETERS: "--to @tinyburg/auto-gold-bits"
          SSH_KEY: ${{ secrets.SSH_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
          TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      - uses: ./.github/workflows/docker-build
        with:
          PROJECT: "auto-gold-bits"
          DOCKERFILE: "./apps/auto-gold-bits/Dockerfile"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
