name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  build-authproxy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Hi Mom
        run: echo "Hi, Mom!"

  build-auto-gold-bits:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Hi Mom
        run: echo "Hi, Mom!"

  build-discord-bot:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Hi Mom
        run: echo "Hi, Mom!"

  build-repl-demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Hi Mom
        run: echo "Hi, Mom!"
