name: CI2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  my-job:
  
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
