name: CI

on:
  push:
    branches: ["main", "renovate/**"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6

      - run: pnpm install
      - run: pnpm clean
      - run: pnpm codegen
      - run: pnpm docgen
      - run: git add packages/**/src && git diff-index --cached HEAD --exit-code packages/**/src
      - run: pnpm check
      - run: pnpm circular
      - run: pnpm lint
      - run: pnpm build
      - run: touch ./.env
      - run: pnpm test
        env:
          NIMBLEBIT_AUTH_KEY: ${{ secrets.NIMBLEBIT_AUTH_KEY }}
